# Copyright 2026 Yogev Neumann
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Yogev Neumann
"""Tests for the assemble_de_bitstring.j2 assembly template.

Tests cover logic that lives in assemble_de_bitstring.j2 itself (Doxygen
wire-format preamble, variable computation) rather than in the sub-templates
it includes.  Sub-template behaviour is verified in their own test files.
"""

from tools.j2735_c_generator_data_element import generate_data_element
from tools.tests.conftest import SpecLoadingTestBase


class TestAssembleBitstringWireFormatDocs(SpecLoadingTestBase):
    """Wire-format Doxygen preamble generated by assemble_de_bitstring.j2."""

    def test_non_extensible_wire_format_doc_no_extension_bit(self) -> None:
        """Non-extensible wire format must not mention extension bit.

        The wire format documentation should reflect that non-extensible types
        have no extension marker, so the total wire size equals root_size.
        """
        code = generate_data_element("LaneDirection", self.spec)
        # Non-extensible 2-bit type should have total wire bits = 2, not 3
        # The Doxygen "Wire Format" header says "3 bits total" — wrong!
        self.assertNotIn(
            "3 bits total",
            code,
            "LaneDirection wire format claims 3 bits total (should be 2)",
        )
        # The "Single-Read Strategy" has "garbage bits: -1" — nonsensical
        self.assertNotIn(
            "-1 garbage bits",
            code,
            "LaneDirection has negative garbage bits (impossible)",
        )
        # There should be no "Ext=0" in non-extensible wire format docs
        self.assertNotIn(
            "Ext=0",
            code,
            "Non-extensible LaneDirection should not mention Ext bit in wire docs",
        )
