# Copyright 2026 Yogev Neumann
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Yogev Neumann
"""Tests for the assemble_de_bitstring.j2 assembly template.

Tests cover logic that lives in assemble_de_bitstring.j2 itself (Doxygen
wire-format preamble, variable computation) rather than in the sub-templates
it includes.  Sub-template behaviour is verified in their own test files.
"""

from tools.j2735_c_generator_data_element import generate_data_element
from tools.tests.conftest import SpecLoadingTestBase


class TestAssembleBitstringWireFormatDocs(SpecLoadingTestBase):
    """Wire-format Doxygen preamble generated by assemble_de_bitstring.j2."""

    def test_non_extensible_wire_format_doc_correct_bit_count(self) -> None:
        """Non-extensible wire format states correct total bit count."""
        code = generate_data_element("LaneDirection", self.spec)
        self.assertIn("2 bits total", code)

    def test_non_extensible_wire_format_doc_no_extension_marker(self) -> None:
        """Non-extensible wire format must not mention extension bit."""
        code = generate_data_element("LaneDirection", self.spec)
        self.assertNotIn("Ext=", code)

    def test_non_extensible_single_read_strategy(self) -> None:
        """Non-extensible single-read strategy uses correct bit width."""
        code = generate_data_element("LaneDirection", self.spec)
        self.assertIn("Single-Read Strategy", code)

    def test_extensible_wire_format_doc_shows_both_forms(self) -> None:
        """Extensible wire format documents both non-extended and extended forms."""
        code = generate_data_element("VehicleEventFlags", self.spec)
        self.assertIn("Non-extended:", code)
        self.assertIn("Extended:", code)

    def test_extensible_wire_format_doc_correct_bit_counts(self) -> None:
        """Extensible wire format shows correct bit counts for both forms."""
        code = generate_data_element("VehicleEventFlags", self.spec)
        self.assertIn("Ext=0", code)
        self.assertIn("Ext=1", code)
