# Copyright 2026 Yogev Neumann
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Yogev Neumann
"""Tests for the assemble_de_bitstring.j2 assembly template.

Tests cover logic that lives in assemble_de_bitstring.j2 itself (Doxygen
wire-format preamble, variable computation) rather than in the sub-templates
it includes.  Sub-template behaviour is verified in their own test files.
"""

from tools.j2735_c_generator_data_element import generate_data_element
from tools.tests.conftest import NON_EXTENSIBLE_BITSTRING_TYPES, SpecLoadingTestBase


class TestAssembleBitstringWireFormatDocs(SpecLoadingTestBase):
    """Wire-format Doxygen preamble generated by assemble_de_bitstring.j2."""

    def test_non_extensible_wire_format_doc_correct_bit_count(self) -> None:
        """Non-extensible wire format states correct total bit count."""
        code = generate_data_element("LaneDirection", self.spec)
        self.assertIn("2 bits total", code)

    def test_non_extensible_wire_format_doc_no_extension_marker(self) -> None:
        """Non-extensible wire format must not mention extension bit."""
        code = generate_data_element("LaneDirection", self.spec)
        self.assertNotIn("Ext=", code)

    def test_non_extensible_single_read_strategy(self) -> None:
        """Non-extensible single-read strategy uses correct bit width."""
        code = generate_data_element("LaneDirection", self.spec)
        self.assertIn("Single-Read Strategy", code)

    def test_extensible_wire_format_doc_shows_both_forms(self) -> None:
        """Extensible wire format documents both non-extended and extended forms."""
        code = generate_data_element("VehicleEventFlags", self.spec)
        self.assertIn("Non-extended:", code)
        self.assertIn("Extended:", code)

    def test_non_extensible_no_constants_banner(self) -> None:
        """Non-extensible output must not emit an empty Constants section."""
        for type_name, _prefix in NON_EXTENSIBLE_BITSTRING_TYPES:
            with self.subTest(type_name=type_name):
                code = generate_data_element(type_name, self.spec)
                self.assertNotIn(
                    "/*  Constants",
                    code,
                    f"{type_name} should not have a Constants banner",
                )

    def test_extensible_has_constants_banner(self) -> None:
        """Extensible output must include the Constants section."""
        code = generate_data_element("VehicleEventFlags", self.spec)
        self.assertIn("/*  Constants", code)

    def test_non_extensible_assembled_uses_bw_not_root_size(self) -> None:
        """Non-extensible assembled output must use J2735_BW_*, not ROOT_SIZE."""
        for type_name, prefix in NON_EXTENSIBLE_BITSTRING_TYPES:
            with self.subTest(type_name=type_name):
                code = generate_data_element(type_name, self.spec)
                self.assertNotIn(
                    f"J2735_INTERNAL_ROOT_SIZE_{prefix}",
                    code,
                    f"{type_name} assembled output should not contain ROOT_SIZE",
                )
                self.assertIn(
                    f"J2735_BW_{prefix}",
                    code,
                    f"{type_name} assembled output should reference J2735_BW_*",
                )

    def test_extensible_assembled_uses_root_size(self) -> None:
        """Extensible assembled output must define ROOT_SIZE."""
        code = generate_data_element("VehicleEventFlags", self.spec)
        self.assertIn("J2735_INTERNAL_ROOT_SIZE_VEHICLE_EVENT_FLAGS", code)

    def test_wire_format_uses_doxygen_code_blocks(self) -> None:
        """Wire format diagrams must be wrapped in @par + @code/@endcode."""
        for type_name, _prefix in NON_EXTENSIBLE_BITSTRING_TYPES:
            with self.subTest(type_name=type_name):
                code = generate_data_element(type_name, self.spec)
                self.assertIn("@par Wire Format", code)
                self.assertIn("@code", code)
                self.assertIn("@endcode", code)

    def test_extensible_wire_format_doc_correct_bit_counts(self) -> None:
        """Extensible wire format shows correct bit counts for both forms."""
        code = generate_data_element("VehicleEventFlags", self.spec)
        self.assertIn("Ext=0", code)
        self.assertIn("Ext=1", code)
